### PR TITLE
Replace Switch Statements with Cleaner Lookups

### PR DESCRIPTION
**Pull request by Ellisande**
Main functionality:
 * Replaced some larger switch statements with smaller lookup functions
 * Moved the lookup functions to their own module

Secondary Functionality:
 * Added unit tests for the new lookups
 * Add mocha/chai to be able to run the tests for the new lookups
 * Added lodash because its crazy useful

Closes: #5

### CODE REVIEW

**Comment by krames12** [comment]
Thanks for adding testing. It was something that I was planning on doing in the near future. I'll have to do some reading up on Lodash but the help and work is definitely appreciated.

**Comment by krames12** [comment]
I definitely should have merged this to a `dev` branch and done some testing before hand. Mistake on my end. I'm going to try and merge this into the `dev` branch if possible and work out the reference error for `lookupClassId`.

**Comment by Ellisande** [comment]
Yeah, I blew it up? Couldn't really test since I don't have your keys. I'll figure it out and submit a patch

**Comment by krames12** [comment]
i'll push it to a branch and make some sense of it lol. The error given was `[ReferenceError: lookupClassId is not defined]`.

**Comment by Ellisande** [comment]
Yeah I found the error, I had written `lookupClassId` instead of `lookupClassName`. Thats what I get for being so reliant on having linter config in a project. I'll make a new PR with the same change minus the bad thing that I did.

When I make the new PR you can clone my fork and test it locally with your API keys, without having to merge it into a dev branch or something.

**Pull request merged**
